### ISSUE TITLE
Users can only see custom hand material on others but not on their own hands.

### ISSUE THREAD

**Issue by MatiasBrunacci** [provencher/MRTK-Online#2]
I tried to replace the hands material of the avatar prefab inside the folder **MRTK-Online** > **Resources** but it seems to be overridden by:

**MixedRealityPlayspace** 
           >> **MRTK-Quest_OVRCameraRig(Clone)**  
                          >>>> **OVRHandPrefab_Left** & **OVRHandPrefab_Right**

The replaced materials load perfectly well on the other players, the problem happens only with the user's hands. 
For instance here in the highFive.gif, the second player is using a black material, but the user is using the default grey one. 

https://user-images.githubusercontent.com/7420990/100374611-8a9f3e00-2fda-11eb-9e48-6e09b7dc238e.gif

Any clue about this issue? 
Thanks in advance @provencher !

**Comment by provencher** [comment]
The oculus device profile has a material reference that's applied to the hands of the local player. That's what you need to change.

**Comment by MatiasBrunacci** [comment]
Thank you for your quick answer! 
Unfortunately, I can't find the "oculus device profile" you mentioned. 
Do you mean the profile inside the **MixedReality Toolkit** gameObject? 

I also noticed this default-grey hand material is created during runtime, as well as the MRTK-Quest_OVRCameraRig(Clone).

**Comment by MatiasBrunacci** [comment]
for the records... solved it just like Eric said by replacing the material inside the **MixedReality Toolkit** gameObject > **Input Data Providers** > **XRSDK Oculus Device Manager** > **Custom Hand Material** 
:)

**Comment by provencher** [comment]
Glad you found it @MatiasBrunacci !

**Comment by hammadshah38** [comment]
@MatiasBrunacci @provencher I want to have more than two persons within the environment. Is there any way to assign different texture to each avatar representing different persons?

Thank you.

**Comment by provencher** [comment]
Yes it’s possible, but it’ll require you to code some behavior around avatars spawning. This is entirely a Normcore situation, so I recommend you read their docs, and if you can’t solve it, ask a question in their discord.

best of luck!

**Comment by hammadshah38** [comment]
> Yes it’s possible, but it’ll require you to code some behavior around avatars spawning. This is entirely a Normcore situation, so I recommend you read their docs, and if you can’t solve it, ask a question in their discord.
> 
> best of luck!

@provencher! Thank you for responding. I will look into it.

**Comment by hammadshah38** [comment]
Hi @provencher. Could you please give me information about how to instantiate a networked manipulatable object on runtime?

Thank you!
