### ISSUE TITLE
Problem in Synchronization

### ISSUE THREAD

**Issue by hammadshah38** [provencher/MRTK-Online#3]
Hi,

I am facing issue related to the objects' state synchronization. Whenever the new user enters the room, state of the networked objects (after manipulation done by existing users) does not change for new user and reset to initial position. If both users enter the room at same time then it is fine. Could you please demonstrate how to update the state of networked objects for new user into the room?

Looking forward to your kind response.

Thank you.

**Comment by provencher** [comment]
This is a Normcore concern, so I recommend you reach out to their discord for questions.

However, for your information I'll explain a few principles.

Object state is managed by users who have ownership over them. When you grab an object in this project, it grants the grabber ownership over the object so they can move them.

If you wish to move them back, you can store the initial position on awake,request ownership and then place them back.

If the last user leaves the room, then the room shuts down a a new room will start up after another group connects. As long as one person remains in the room, the state will persist.

If you wish to start a fresh session, you can also have users connect to a different room id. I recommend reading Normcore docs to understand how rooms work.
