### ISSUE TITLE
Object Manipulator and Networked Manipulator turn off isKinematic

### ISSUE THREAD

**Issue by reeseras** [provencher/MRTK-Online#4]
I can't get this to consistently happen, so I'm not entirely sure how it works.

**Here's the method:**

Create an empty with 2 objects (cube and cylinder). Create an empty as a child of the cylinder and add a collider to it (check "isTrigger" and move the collider so the cube could touch it when moved). Add the following components to the cube: Rigidbody (gravity is off, kinematic is on), Realtime Transform, Networked Manipulator, Object Manipulator, and Near Interaction Grabbable. _Now here's the inconsistent part:_ pick up the cube from a distance and move it rapidly over/through/around/inside the trigger collider. You might have to let go of it a few times inside the collider (or outside the collider?) Eventually, the cube will start to float. Inspect the cube to see isKinematic is turned off. Resetting the game turns it back on.

**Comment by provencher** [comment]
This is likely a Normcore issue. I'd join their discord to discuss it with them.

Not much I can do here.

**Comment by reeseras** [comment]
I tried that, they said it was an MRTK issue.

**Comment by reeseras** [comment]
![image](https://user-images.githubusercontent.com/26148056/113785136-ccac5f00-96f3-11eb-806a-3acc1b9dc9da.png)

**Comment by provencher** [comment]
Interesting. Well in that case I'd recommend opening an issue with MRTK 

https://github.com/microsoft/MixedRealityToolkit-Unity

**Comment by reeseras** [comment]
I'll try that, but I bet they'll say something about contacting normcore as well. Thanks for the quick response!

**Comment by provencher** [comment]
This repo doesn't affect kinematic. The only thing it does is request ownership of the realtime component following MRTK interaction events.
