### ISSUE TITLE
Oculus Quest vs Oculus Quest 2

### ISSUE THREAD

**Issue by hammadshah38** [provencher/MRTK-Online#6]
Hi,
Thank you so much for nice project.
I am using Oculus Quest and this project is working fine with that. I have to order an Oculus Quest 2. I wanted to know if this project works for Oculus Quest 2 as well?
It would be so nice of you if you can respond as soon as possible, as I have to place an order.
Thank you

**Comment by provencher** [comment]
Yep! Works great on Quest 2 as well :)
